linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  goimports:
    local-prefixes: github.com/clastix/capsule-proxy
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
linters:
  enable-all: true
  disable:
    - gomnd
    - goerr113
    - exhaustivestruct
    - lll

service:
  golangci-lint-version: 1.33.x
