apiVersion: v1
kind: Service
metadata:
  name: {{ include "capsule-proxy.fullname" . }}
  labels:
    {{- include "capsule-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: http
  selector:
    {{- include "capsule-proxy.selectorLabels" . | nindent 4 }}
